export const LANDING = "/";
export const SIGNUPPAGE = "/auth/signup";
export const LOGINPAGE = "/auth/login";
export const PROTECTEDPAGE = "/protected"
export const HOME = "/home";
export const USER = "/profile/user/detailUser";//add id later
export const FAVORITES = "/favorite/findfavorites";//createbakend elistfavs
export const PLACES = "/places/enlistplaces";
export const PENDING = "/places/pending";
export const DONE = "/places/done";
export const LOGOUT = "/auth/logout";
export const CREATEPLACES = "/places/createplaces";
export const EDITPLACES = "/places/editplaces";
export const EDITUSER = "/user/editUser"
export const EDITPASSWORD = "/user/editPassword"
