export const LANDING = "/";
export const SIGNUPPAGE = "/auth/signup";
export const LOGINPAGE = "/auth/login";
export const PROTECTEDPAGE = "/protected"
export const HOME = "/home";
export const USER = "/profile/user/detailUser/:id";//add id later
export const FAVORITES = "/favorite/findfavorites";//createbakend elistfavs
export const PLACES = "/places/enlistplaces";
export const PENDING = "/places/pending";
export const DONE = "/places/done";
export const LOGOUT = "/logout";
export const CREATEPLACES = "/places/createplaces";
export const EDITPLACES = "/places/editplaces/:id";
export const EDITUSER = "/user/editUser/:id"
